## YAML Template.
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/libreria
    username: agustin
    password: 200500123a
    jpa:
    show-sql: false
    hibernate:
      ddl-auto: update    
  thymeleaf:
    cache: false 
server:
  error:
    whitelabel:
      enabled: false
